### ISSUE TITLE
Unable to build using install.sh - BOOST_CONCEPT_USAGE - "failed updating 1 target"

### ISSUE THREAD

**Issue by moznc** [libbitcoin/libbitcoin-system#1371] opened 2023-08-30 19:44 UTC
**Unable to build using install.sh**

**Description**:
Unable to build using install.sh, the build always ends here:
```
$ sudo ./install.sh --with-icu --build-icu --build-boost --prefix=/home/debian/apps/bitcoin/libbitcoin --verbose
...
./boost/concept/usage.hpp:30:7: note: in a call to non-static member function ‘boost::SinglePassRangeConcept<T>::~SinglePassRangeConcept() [with T = const boost::iterator_range<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >]’
   30 |       ~model()
      |       ^
./boost/range/concepts.hpp:284:9: note: in expansion of macro ‘BOOST_CONCEPT_USAGE’
  284 |         BOOST_CONCEPT_USAGE(SinglePassRangeConcept)
      |         ^~~~~~~~~~~~~~~~~~~
...failed updating 1 target...

real	5m40.369s
user	10m25.931s
sys	1m30.737s
```

**Steps to Reproduce**:
```
$ sudo apt-get install build-essential autoconf automake libtool pkg-config git
$ wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/version3/install.sh
$ chmod +x install.sh
$ sudo ./install.sh --with-icu --build-icu --build-boost --prefix=/home/debian/apps/bitcoin/libbitcoin --verbose
```

**Environment**:
- Operating System: Debian Bookworm
- clang++: 14.0.6
- g++: 12.2.0
- automake: 1.16.5
- autoconf: 2.71

**Comment by pmienk** [comment] 2023-08-31 05:21
@moznc More information is required. Please provide additional build output.

**Comment by moznc** [comment] 2023-08-31 06:05
Sure @pmienk: [moznc-libbitcoin-build-log.txt.zip](https://github.com/libbitcoin/libbitcoin-system/files/12482762/moznc-libbitcoin-build-log.txt.zip)


I removed the _--prefix_ option to install the lib in its default location and ran this command:
`$ sudo ./install.sh --with-icu --build-icu --build-boost --verbose`

**Comment by pmienk** [comment] 2023-08-31 08:02
@moznc This is a failure to build the dependency boost 1.72.0 on your platform. The relevant error is found above and relates to `PTHREAD_STACK_MIN` declaration and is a duplicate to #1370

**Comment by pmienk** [comment] 2023-08-31 08:22
Closing as duplicate of #1370

**Closed by pmienk** 2023-08-31 08:22 UTC
Labels: build
