### ISSUE TITLE
Build failing on Fedora and Manjaro (ArchLinux)

### ISSUE THREAD

**Issue by UniversalBinary** [libbitcoin/libbitcoin-system#1130] opened 2019-08-18 20:40 UTC
I have attempted to build libbitcoin using install.sh on a Fedora Linux (x86_64) and on   Manjaro (arm64) system. Both builds failed with exactly the same issue. Below is the output leading up to the failure:

```
019-08-18 20:57:34 (3.08 MB/s) - ‘boost_1_62_0.tar.bz2’ saved [84513338/84513338]

Libbitcoin boost configuration.
--------------------------------------------------------------------
variant               : release
threading             : multi
toolset               : 
cxxflags              : 
linkflags             : 
link                  : static
boost.locale.iconv    : off
boost.locale.posix    : off
-sNO_BZIP2            : 1
-sICU_PATH            : /home/chris/.local
-sICU_LINK            : -licui18n -L/home/chris/.local/lib -licuuc -licudata -ldl
-sZLIB_LIBPATH        : /home/chris/.local/lib
-sZLIB_INCLUDE        : /home/chris/.local/include
-j                    : 4
-d0                   : [supress informational messages]
-q                    : [stop at the first error]
--reconfigure         : [ignore cached configuration]
--prefix              : /home/chris/.local
BOOST_OPTIONS         : --with-atomic --with-chrono --with-date_time --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-regex --with-system --with-thread --with-test
--------------------------------------------------------------------
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxarm/b2
Detecting Python version... 3.7
Detecting Python root... /usr
Unicode/ICU support for Boost.Regex?... /home/chris/.local
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html


usage: ./b2 [ options ] targets...

-a      Build all targets, even if they are current.
-dx     Set the debug level to x (0-9).
-fx     Read x instead of Jambase.
-jx     Run up to x shell commands concurrently.
-lx     Limit actions to x number of seconds after which they are stopped.
-mx     Maximum target output saved (kb), default is to save all output.
-n      Don't actually execute the updating actions.
-ox     Mirror all output to file x.
-px     x=0, pipes action stdout and stderr merged into action output.
-q      Quit quickly as soon as a target fails.
-sx=y   Set variable x=y, overriding environment.
-tx     Rebuild x, even if it is up-to-date.
-v      Print the version of jam and exit.
--x     Option is ignored.

Invalid option: -L

real	14m49.625s
user	22m20.689s
sys	2m30.700s
```

**Comment by thecodefactory** [comment] 2019-08-18 21:36
@UniversalBinary Thanks for reporting.  Are you using the latest Fedora version?  I'll see about setting up a VM to see what's going on there.

**Comment by evoskuil** [comment] 2019-08-19 00:59
Looks like `b2` doesn't like an uppercase `-L` option, as the other succeed. I'm not sure why we generate that as upper case as distinct from the other `-sICU_LINK` options.

**Comment by UniversalBinary** [comment] 2019-08-19 09:25
It was the latest version of Fedora, although you seem to have located the problem anyway.

**Comment by thecodefactory** [comment] 2019-08-20 02:14
I was able to reproduce this easily on Fedora 30 as described.  Added a fix to the open build PR: https://github.com/libbitcoin/libbitcoin-build/pull/201/commits/aeae9a6f4094ac2cb72937e871bf50c9c7b908a0

**Comment by evoskuil** [comment] 2019-08-30 06:19
Resolved?

**Comment by thecodefactory** [comment] 2019-08-30 12:39
@evoskuil This has been resolved in all version3 repo branches.  I'll close this after completing the same for master (starting with https://github.com/libbitcoin/libbitcoin-build/pull/203)

**Closed** 2019-08-30 13:38 UTC
Labels: build
